-- MySQL Script generated by MySQL Workbench
-- 04/05/16 11:46:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema artsandcrafts
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `artsandcrafts` ;

-- -----------------------------------------------------
-- Schema artsandcrafts
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `artsandcrafts` DEFAULT CHARACTER SET utf8 ;
USE `artsandcrafts` ;

-- -----------------------------------------------------
-- Table `artsandcrafts`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `artsandcrafts`.`Customer` ;

CREATE TABLE IF NOT EXISTS `artsandcrafts`.`Customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(70) NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artsandcrafts`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `artsandcrafts`.`Address` ;

CREATE TABLE IF NOT EXISTS `artsandcrafts`.`Address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `description` VARCHAR(70) NULL,
  `address` VARCHAR(255) NOT NULL,
  `is_billing_address` TINYINT(1) NULL,
  `is_active` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Address_Customer1_idx` (`customer_id` ASC),
  CONSTRAINT `fk_Address_Customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `artsandcrafts`.`Customer` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artsandcrafts`.`Invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `artsandcrafts`.`Invoice` ;

CREATE TABLE IF NOT EXISTS `artsandcrafts`.`Invoice` (
  `id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Invoice_Customer1_idx` (`customer_id` ASC),
  CONSTRAINT `fk_Invoice_Customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `artsandcrafts`.`Customer` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artsandcrafts`.`Service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `artsandcrafts`.`Service` ;

CREATE TABLE IF NOT EXISTS `artsandcrafts`.`Service` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address_id` INT NOT NULL,
  `invoice_id` INT NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `cost` DECIMAL(10,2) NOT NULL,
  `start` DATETIME NOT NULL,
  `end` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Service_Address_idx` (`address_id` ASC),
  INDEX `fk_Service_Invoice1_idx` (`invoice_id` ASC),
  CONSTRAINT `fk_Service_Address`
    FOREIGN KEY (`address_id`)
    REFERENCES `artsandcrafts`.`Address` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Service_Invoice1`
    FOREIGN KEY (`invoice_id`)
    REFERENCES `artsandcrafts`.`Invoice` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artsandcrafts`.`RecurringTime`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `artsandcrafts`.`RecurringTime` ;

CREATE TABLE IF NOT EXISTS `artsandcrafts`.`RecurringTime` (
  `id` INT NOT NULL,
  `day` INT NOT NULL,
  `week` VARCHAR(10) NULL,
  `month` INT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artsandcrafts`.`RecurringService`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `artsandcrafts`.`RecurringService` ;

CREATE TABLE IF NOT EXISTS `artsandcrafts`.`RecurringService` (
  `id` INT NOT NULL,
  `address_id` INT NOT NULL,
  `description` VARCHAR(255) NULL,
  `cost` DECIMAL(10,2) NULL,
  `frequency_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ReoccuringService_Address1_idx` (`address_id` ASC),
  INDEX `fk_RecurringService_RecurringTime1_idx` (`frequency_id` ASC),
  CONSTRAINT `fk_ReoccuringService_Address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `artsandcrafts`.`Address` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RecurringService_RecurringTime1`
    FOREIGN KEY (`frequency_id`)
    REFERENCES `artsandcrafts`.`RecurringTime` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artsandcrafts`.`Payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `artsandcrafts`.`Payment` ;

CREATE TABLE IF NOT EXISTS `artsandcrafts`.`Payment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  `description` VARCHAR(75) NULL,
  `amount` DECIMAL(10,2) NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Payment_Customer1_idx` (`customer_id` ASC),
  CONSTRAINT `fk_Payment_Customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `artsandcrafts`.`Customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
